---
title: "An Open Source Exploration of a Semantic Structure for Climate Accounting"
author: "Christiaan Pauw and Alex Howard"
date: "01/06/2022"
output:
  powerpoint_presentation:
  ioslides_presentation:
    toc: yes
    incremental: yes
    keep_md: yes
  slidy_presentation: 
    incremental: yes
    keep_md: yes
  beamer_presentation:
    toc: no
    includes:
      in_header: header.tex
    incremental: no
    theme: Montpellier
    slide_level: 2
    colortheme: whale
    fonttheme: professionalfonts
header-includes:
  - \AtBeginDocument{\title[A Semantic Structure for Climate Accounting]{An Open Source Exploration of a Semantic Structure for Climate Accounting}}
  - \setbeamertemplate{section in toc}[]
  - \setbeamertemplate{subsection in toc}[subsections numbered]
  - \setbeamertemplate{footline}[frame number]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- # Abstract
decide when to use 'semantic structure', 'ontology' or 'taxonomy'--> 

<!-- As the world accelerates towards decarbonisation, the need for climate impact accounting at scale becomes more pressing. One of the greatest challenges in this regard is the description, comparison and aggregation of impact claims due to the multitude of existing accounting and reporting standards. The reconciliation and aggregation of these claims, in the interest of climate impact “bookkeeping” at a global scale, requires a common underlying semantic structure – which currently does not exist. 

The Standards Working Group (Standards WG) of the Hyperledger Climate Action and Accounting Special Interest Group (CA2-SIG) aims to lay out such a semantic structure. Working from the premise that agents engage in activities that impact environments, the WG is actively searching out standards to distil their semantic structures into an ontology that most adequately describes these elements and the relationships between them. The ontology is by design open source, collaborative, dynamic and technology agnostic. 

The presentation will provide: 

  * an overview of the WG's work to date,
  * introduce the latest version of the basic ontology, and 
  * demonstrate the ontology's application by means of an exemplary use case. 
-->

<!--
1. Background. 
2. Brief overview of existing standards. 
3. An exercise in comparing and aggregating impact claims based on different standards, without the use of a common ontology. 
4. Introduction to the ontology being developed by the Hyperledger CA2-SIG Standards WG. 
5. An exercise in applying the ontology to climate impact accounting. 
6. A brief exploration of the application of the ontology in other fields of impact accounting. 
7. Conclusion & how to get involved.
-->


# The challenge


* To avoid catastrophic climate change, we need to dramatically reduce greenhouse gas emissions and increase carbon sinks

* For these processes to be managed, climate accounting must become ubiquitous

* For climate accounting to become ubiquitous, the individual instances must interoperable

* But, there are different practises, protocols and standards that are used for different purposes ...

<!--
As the world accelerates towards decarbonisation, the need for climate impact accounting at scale becomes more pressing. One of the greatest challenges in this regard is the description, comparison and aggregation of impact claims due to the multitude of existing accounting and reporting standards. The reconciliation and aggregation of these claims, in the interest of climate impact “bookkeeping” at a global scale, requires a common underlying semantic structure – which currently does not exist.

Standards, protocols, taxonomies and ontologies
What is the difference between 'semantic structure', 'ontology' and 'taxonomy'?
-->
## Interoperability

#### What is interoperability?

"Able to make use of information"

#### Hierarchy of interoperability

*Description:*
  Requires stable terminology

*Comparison:* 
  Express in the same terminology

*Aggregation:*
  Express in the same metric

___

### Description and discovery

Describing or discovering impact is a challenge because different words mean different things to different people.

**Terms** like  *The environment* , *Climate neutral* and *Carbon Neutral* are commonly used but do not always denote to the same thing. 

People are guided by different **interests** when speaking about impact
<!-- An extreme example is the difference between *marketing-speak* and environmental fear-mongering. One form of speaking tend to understate negative impacts and overstate benefits, the other tends to overstate risks. -->

A global system of machine-readable claims about environmental impacts, without a shared language will either only exasperate the confusion or it will fragment into a myriad of definition sets and reporting formats for every interest group.

<!-- Discovery -->

___

### Comparison 

Comparing is difficult because there are differences in:

* *What* is accounted for, and 

* *How* accounting takes place

**What is accounted for:**
  E.g. Differences in:
  
  * organisational boundaries, 
  
  * activity boundaries, 
  
  * greenhouse agents

**How accounting is done: **
  
  * Even where above corresponds, calculation methods may differ

____

#### Example: Two improved cookstoves project in the South Africa lowveld


Even things that look the same are not the same:

Compare two project that both operate in the voluntary market, both involve improved cookstoves and both are located in South Africa.

Fuel Efficient Cooking in South Africa (VCS 2505) 
Brickstar Wood Stove - Mahlaba Area (GS4536)

___

They differ in important ways:

* One encompasses the whole country, one a specific region

* One estimates the baseline wood use from a naive calculation using generic, country level data, the other from household surveys empirical observations.

* Different methodologies: Verra:VMR006 and Gold Standard:TPDDTEC

There is no simple way to compare these two projects

___

### Aggregation

It follows that *aggregation* is difficult when *description* and *comparison* are problematic

Aggregation can only work if all assumptions are made explicit. E.g. accounting period, emission factors

Lack of clarity uncertainty leads to blurring and semantic "zoom-out"


# Maybe Standards is the solution... ?

### What are standards for?

<!-- Standards are agreements to guide “common and repeated use of rules, conditions, guidelines or characteristics for products or related processes and production methods, and related management systems practices” -->

Standards aggregate *norms* that help shape interests, constrain behaviour, prescribe actions, and support a logic of appropriateness and consequences.

Norms are social constructs that emerge from persuasion, cascade through acceptance, and internalize compliant behaviour.

<!-- Standard documents include “definition of terms; classification of components; delineation of procedures; specification of dimensions, materials, performance, designs, or operations; measurement of quality and quantity; test methods and sampling procedures; or descriptions of fit and measurements of size or strength.”

Source: https://en.wikipedia.org/wiki/Technical_standard + "Developing Operational Requirements: A Guide to the Cost-Effective and Efficient Communication of Needs" (PDF). US Department of Homeland Security. November 2008 -->

<!-- which aspects of reality to be represented, form of that representation , 
roles and responsibilities of agents  --> 

### Different standards have different aims

<!-- extract or derive objectives of each standard -->

___

### Examples of interests

#### Perspective of investor 
Announced at COP26 in November 2021, the ISSB is a first step in developing a global, baseline, corporate reporting standard on climate change and sustainability. It aims to provide investors and other capital market participants with information about companies’ sustainability-related risks and opportunities to help them make informed decisions. 
*Forging the path to international standards in sustainable finance. 2022 OMFIF.* [https://www.omfif.org/forging-the-path-to-international-standards-in-sustainable-finance/]

#### Regulatory perspective 
Compliance to international treaties (EU, Paris) and local laws and regulations

"The Paris Agreement sets out a global framework to avoid dangerous climate change by limiting global warming to well below 2°C and pursuing efforts to limit it to 1.5°C. It also aims to strengthen countries' ability to deal with the impacts of climate change and support them in their efforts."

___

#### Voluntary climate action
"The Gold Standard (GSF) was established in 2003 by WWF and other international NGOs to ensure projects that reduced carbon emissions featured the highest levels of environmental integrity and also contributed to sustainable development."

"The VCS Program allows certified projects to turn their greenhouse gas (GHG) emission reductions and removals into tradable carbon credits. "

(-- narrow or broad context)
 
#### Project or institutional focus

Some activities are undertaken for the express purpose of achieving a social or environmental impact. Such activities are accounted for different compared to the normal operations of a business.  

The *WBCSD/WRI GHG Protocol* contains and *GHG Project Protocol* for projects (i.e. undertaken with the express purpose of having environmental impact), and a *GHG Protocol Corporate Accounting and Reporting Standard *, for corporate-level GHG emissions inventories. 

___

## Standards use different metrics

<!-- extract or derive metrics used of various standard (see GHG protocol for performance standard approach -->

Impacts can be described using different metrics:

 * Performance standard (resource efficiency per output)
 
 * Emission reduction / avoidance 
 
 * Net emissions

**Performance standard** is about efficiency and takes into account that there are simultaneous but possibly competing goals. Aims for most efficient 

**Emission avoidance** compares what happened against what would have happened (i.e. a counterfactual baseline). Aims to better than baseline

**Net emissions** balances carbon sinks and carbon emission. Aims for net zero / negative

___

## Examples of standards in use
<!-- Kyle -->

Sustainability Accounting Standards Board

Task Force on Climate-Related Financial Disclosure

Global Reporting Initiative (GRI) - 
  * Universal standards, sector standards, topic standards

ISSB

Climate Disclosure Standard Board 
  (importance of policy, strategy, management and scenario analysis )

WEF

IR

___

## Example: Comparison of standards

(Alex)
CDM: https://cdm.unfccc.int/filestorage/e/x/t/extfile-20210921115752581-reg_stan04_v03.0.pdf/reg_stan04_v03.0?t=QjB8cmM0ZDRnfDBV7GVs5k5cf3k7WEJwicbL

Implied taxonomy or semantic structure 

Compare two reports (same company) or two companies according to two standards 

___

## The need for a "deep" shared ontology

### Maybe standardisation is not the solution, because:

* There are different needs and interests and always will be there 

* A prescriptive approach is inappropriate and will not work anyway

### Find the concenptual bedrock that underlies all the standard

Html example (power of consensus on profoundly simple, opportunity-generating, enabling standards)

Burners Lee

FIN sector example (OMFIF article) <!-- CJP check -->




# A semantic structure for climate accounting

## Premise of our ontology

(Not another standard )

Agent - activity - environment

### Agent

### Activity

### Environment

### Applicability to *impact accounting* in general 
(skuif)

Carbon tunnel vision

planetary well-being



___

## Ontology diagram

___

## How we envision our ontology can be used: 

All operations require standardisation as a starting point

<!-- * A standard is a query OR a presentation -->

<!-- VC presentation according to a standard -->

### Use of the ontology: Description

The ontology helps us be precise  .....

### Use of the ontology: Comparison 

The ontology helps translate .... (Rosetta Stone)

### Use of the ontology: Aggregation

Improve the IWA .....

It follows that the more precise and comparable, ... 

# What's next and how to get involved

(what's next)

(feedback)

(contacts, and channels)

(wiki)

# Acknowledgements

Thanks to contributes:

Alfono Govella: 

Kyle Robinson: 

# Sources 

https://interwork.org/wp-content/uploads/2021/05/Voluntary_Ecological_Markets_Overview_Revised.pdf

https://gml.noaa.gov/ccgg/trends/mlo.html
