name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - Schemas/OWL/aia.owl

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python and pyLODE
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'  # Enable caching for pip

    - name: Install pyLODE if not cached
      run: |
        python -m pip install --upgrade pip
        pip install pylode

    - name: Generate Documentation
      run: |
        if [ ! -d Documentation ]; then mkdir -p Documentation; fi  # Create Documentation folder if it doesn't exist
        pylode -o Documentation/index.html Schemas/OWL/aia.owl

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Documentation/index.html
        git commit -m 'Update documentation for aia.owl'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
